
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  

development:
  <<: *default
  database: inventory_development

production:
  <<: *default
  database: inventory_production
  username: inventory
  password: <%= ENV['INVENTORY_DATABASE_PASSWORD'] %>


